"""
This type stub file was generated by pyright.
"""

from .base import ANY, NamedSignal, Namespace, Signal, default_namespace, signal

__all__ = ["ANY", "default_namespace", "NamedSignal", "Namespace", "Signal", "signal"]
