#!/bin/sh

set -eu

: ${CLEAN:=0}

TOP_BUILD_DIR=_build

if [ "$CLEAN" -eq 1 ]; then
    rm -rf "$TOP_BUILD_DIR"/*
fi

compile_commands_path=compile_commands.json

sound () {
    cd "$TOP_BUILD_DIR"

    export PICO_SDK_PATH=/usr/share/pico-sdk

    cmake -DPICO_BOARD=pico2_w -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_VERBOSE_MAKEFILE=OFF ..

    # make V=1
    cmake --build . --parallel 6

    cd -

    mv "$TOP_BUILD_DIR/compile_commands.json" "$compile_commands_path"
}

sound_install () {
    picotool load -f "$TOP_BUILD_DIR/picomigo_sound_demo.uf2" && \
    picotool reboot
}

sound_module () {
    ./do_build_module
}

. ./.build

step="${1:-all}"

if [ "$step" = all ]; then
    sound

    sound_module
else
    "$step"
fi
