FROM registry.mahnke.tech/mktech/build:latest

RUN --mount=type=cache,id=pacman-cache,target=/var/cache/pacman,sharing=locked \
    pacman --noconfirm -Syu \
    udisks2 \
    arm-none-eabi-gcc \
    cmake \
    gcc14

# aur picotool arm-none-eabi-newlib

# RUN pacman --noconfirm -Scc

ARG source_name=picomigo
ARG source_dir=/usr/local/src/$source_name

RUN mkdir -p $source_dir && chmod 777 $source_dir

WORKDIR $source_dir

COPY . .
