[project]
name = "picomigo"
version = "0.1.0"
description = ""
authors = [{name = "Fritz Mahnke", email = "fritz@mahnke.tech"}]
license = {text = "GPL-3.0"}
readme = "README.md"
requires-python = ">=3.13"
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Documentation",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = [
    "ar>=1.0.0",
    "click>=8.1.7",
    "mktech",
    "mpremote>=1.25.0",
    "pyelftools>=0.32",
    "rshell>=0.0.36",
]

[project.urls]
Homepage = "https://fmahnke.github.io/picomigo"
Documentation = "https://fmahnke.github.io/picomigo"
Changelog = "https://fmahnke.github.io/picomigo/changelog"
Repository = "https://github.com/fmahnke/picomigo"
Issues = "https://github.com/fmahnke/picomigo/issues"
Discussions = "https://github.com/fmahnke/picomigo/discussions"

[project.scripts]
picomigo = "picomigo.cli:main"

[project.optional-dependencies]
serial = [
    "pyserial>=3.5",
]

[dependency-groups]
dev = [
    "micropython-rp2-rpi-pico2-w-stubs>=1.25.0.post4",
    "mktech-dev-tools[check,debug,doc,lsp-pyright,lsp-python-lsp-server] @ git+http://git.mahnke.tech/lib/python/mktech/dev-tools.git@0.1.0",
]

[tool.coverage.run]
branch = true
parallel = true
source = [ "src" ]

[tool.pylsp-mypy]
enabled = false
follow-imports = "normal"

[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.uv.sources]
mktech = { git = "http://git.mahnke.tech/lib/python/mktech/mktech.git", rev = "0.22.0-dev" }

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
