"""
This type stub file was generated by pyright.
"""

import struct
from math import cos, sin
from time import sleep_ms
"""
MIT License

Copyright (c) 2020-2023 Russ Hughes

Copyright (c) 2019 Ivan Belokobylskiy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

The driver is based on devbis' st7789py_mpy module from
https://github.com/devbis/st7789py_mpy.

This driver supports:

- 320x240, 240x240, 135x240 and 128x128 pixel displays
- Display rotation
- RGB and BGR color orders
- Hardware based scrolling
- Drawing text using 8 and 16 bit wide bitmap fonts with heights that are
  multiples of 8.  Included are 12 bitmap fonts derived from classic pc
  BIOS text mode fonts.
- Drawing text using converted TrueType fonts.
- Drawing converted bitmaps
- Named color constants

  - BLACK
  - BLUE
  - RED
  - GREEN
  - CYAN
  - MAGENTA
  - YELLOW
  - WHITE

"""

from types import ModuleType

from machine import SPI

_ST7789_SWRESET = ...
_ST7789_SLPIN = ...
_ST7789_SLPOUT = ...
_ST7789_NORON = ...
_ST7789_INVOFF = ...
_ST7789_INVON = ...
_ST7789_DISPOFF = ...
_ST7789_DISPON = ...
_ST7789_CASET = ...
_ST7789_RASET = ...
_ST7789_RAMWR = ...
_ST7789_VSCRDEF = ...
_ST7789_COLMOD = ...
_ST7789_MADCTL = ...
_ST7789_VSCSAD = ...
_ST7789_RAMCTL = ...
_ST7789_MADCTL_MY = ...
_ST7789_MADCTL_MX = ...
_ST7789_MADCTL_MV = ...
_ST7789_MADCTL_ML = ...
_ST7789_MADCTL_BGR = ...
_ST7789_MADCTL_MH = ...
_ST7789_MADCTL_RGB = ...
RGB = ...
BGR = ...
_COLOR_MODE_65K = ...
_COLOR_MODE_262K = ...
_COLOR_MODE_12BIT = ...
_COLOR_MODE_16BIT = ...
_COLOR_MODE_18BIT = ...
_COLOR_MODE_16M = ...
BLACK = ...
BLUE = ...
RED = ...
GREEN = ...
CYAN = ...
MAGENTA = ...
YELLOW = ...
WHITE = ...
_ENCODE_PIXEL = ...
_ENCODE_PIXEL_SWAPPED = ...
_ENCODE_POS = ...
_ENCODE_POS_16 = ...
_BUFFER_SIZE = ...
_BIT7 = ...
_BIT6 = ...
_BIT5 = ...
_BIT4 = ...
_BIT3 = ...
_BIT2 = ...
_BIT1 = ...
_BIT0 = ...
_DISPLAY_240x320 = ...
_DISPLAY_240x240 = ...
_DISPLAY_135x240 = ...
_DISPLAY_128x128 = ...
_WIDTH = ...
_HEIGHT = ...
_XSTART = ...
_YSTART = ...
_NEEDS_SWAP = ...
_SUPPORTED_DISPLAYS = ...
_ST7789_INIT_CMDS = ...


def color565(red: int, green: int = ..., blue: int = ...) -> int:
    """
    Convert red, green and blue values (0-255) into a 16-bit 565 encoding.
    """
    ...


class ST7789:
    """
    ST7789 driver class

    Args:
        spi (spi): spi object **Required**
        width (int): display width **Required**
        height (int): display height **Required**
        reset (pin): reset pin
        dc (pin): dc pin **Required**
        cs (pin): cs pin
        backlight(pin): backlight pin
        rotation (int):

          - 0-Portrait
          - 1-Landscape
          - 2-Inverted Portrait
          - 3-Inverted Landscape

        color_order (int):

          - RGB: Red, Green Blue, default
          - BGR: Blue, Green, Red

        custom_init (tuple): custom initialization commands

          - ((b'command', b'data', delay_ms), ...)

        custom_rotations (tuple): custom rotation definitions

          - ((width, height, xstart, ystart, madctl, needs_swap), ...)

    """

    physical_width: int
    physical_height: int
    width: int
    height: int
    spi: SPI

    def __init__(
        self,
        spi,
        width,
        height,
        reset=...,
        dc=...,
        cs=...,
        backlight=...,
        rotation=...,
        color_order=...,
        custom_init=...,
        custom_rotations=...
    ) -> None:
        """
        Initialize display.
        """
        ...

    def init(self, commands) -> None:
        """
        Initialize display.
        """
        ...

    def hard_reset(self) -> None:
        """
        Hard reset display.
        """
        ...

    def soft_reset(self) -> None:
        """
        Soft reset display.
        """
        ...

    def sleep_mode(self, value: bool) -> None:
        """
        Enable or disable display sleep mode.

        Args:
            value (bool): if True enable sleep mode. if False disable sleep
            mode
        """
        ...

    def inversion_mode(self, value: bool) -> None:
        """
        Enable or disable display inversion mode.

        Args:
            value (bool): if True enable inversion mode. if False disable
            inversion mode
        """
        ...

    def rotation(self, rotation: int) -> None:
        """
        Set display rotation.

        Args:
            rotation (int):
                - 0-Portrait
                - 1-Landscape
                - 2-Inverted Portrait
                - 3-Inverted Landscape

            custom_rotations can have any number of rotations
        """
        ...

    def vline(self, x: int, y: int, length: int, color: int) -> None:
        """
        Draw vertical line at the given location and color.

        Args:
            x (int): x coordinate
            Y (int): y coordinate
            length (int): length of line
            color (int): 565 encoded color
        """
        ...

    def hline(self, x: int, y: int, length: int, color: int) -> None:
        """
        Draw horizontal line at the given location and color.

        Args:
            x (int): x coordinate
            Y (int): y coordinate
            length (int): length of line
            color (int): 565 encoded color
        """
        ...

    def pixel(self, x: int, y: int, color: int) -> None:
        """
        Draw a pixel at the given location and color.

        Args:
            x (int): x coordinate
            Y (int): y coordinate
            color (int): 565 encoded color
        """
        ...

    def blit_buffer(
        self, buffer, x: int, y: int, width: int, height: int
    ) -> None:
        """
        Copy buffer to display at the given location.

        Args:
            buffer (bytes): Data to copy to display
            x (int): Top left corner x coordinate
            Y (int): Top left corner y coordinate
            width (int): Width
            height (int): Height
        """
        ...

    def rect(self, x: int, y: int, w: int, h: int, color: int) -> None:
        """
        Draw a rectangle at the given location, size and color.

        Args:
            x (int): Top left corner x coordinate
            y (int): Top left corner y coordinate
            width (int): Width in pixels
            height (int): Height in pixels
            color (int): 565 encoded color
        """
        ...

    def fill_rect(
        self, x: int, y: int, width: int, height: int, color: int
    ) -> None:
        """
        Draw a rectangle at the given location, size and filled with color.

        Args:
            x (int): Top left corner x coordinate
            y (int): Top left corner y coordinate
            width (int): Width in pixels
            height (int): Height in pixels
            color (int): 565 encoded color
        """
        ...

    def fill(self, color: int) -> None:
        """
        Fill the entire FrameBuffer with the specified color.

        Args:
            color (int): 565 encoded color
        """
        ...

    def line(self, x0: int, y0: int, x1: int, y1: int, color: int) -> None:
        """
        Draw a single pixel wide line starting at x0, y0 and ending at x1, y1.

        Args:
            x0 (int): Start point x coordinate
            y0 (int): Start point y coordinate
            x1 (int): End point x coordinate
            y1 (int): End point y coordinate
            color (int): 565 encoded color
        """
        ...

    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None:
        """
        Set Vertical Scrolling Definition.

        To scroll a 135x240 display these values should be 40, 240, 40.
        There are 40 lines above the display that are not shown followed by
        240 lines that are shown followed by 40 more lines that are not shown.
        You could write to these areas off display and scroll them into view by
        changing the TFA, VSA and BFA values.

        Args:
            tfa (int): Top Fixed Area
            vsa (int): Vertical Scrolling Area
            bfa (int): Bottom Fixed Area
        """
        ...

    def vscsad(self, vssa: int) -> None:
        """
        Set Vertical Scroll Start Address of RAM.

        Defines which line in the Frame Memory will be written as the first
        line after the last line of the Top Fixed Area on the display

        Example:

            for line in range(40, 280, 1):
                tft.vscsad(line)
                utime.sleep(0.01)

        Args:
            vssa (int): Vertical Scrolling Start Address

        """
        ...

    def text(
        self,
        font: ModuleType,
        text: str,
        x0: int,
        y0: int,
        color: int = ...,
        background: int = ...
    ) -> None:
        """
        Draw text on display in specified font and colors. 8 and 16 bit wide
        fonts are supported.

        Args:
            font (module): font module to use.
            text (str): text to write
            x0 (int): column to start drawing at
            y0 (int): row to start drawing at
            color (int): 565 encoded color to use for characters
            background (int): 565 encoded color to use for background
        """
        ...

    def bitmap(
        self, bitmap: ModuleType, x: int, y: int, index: int = ...
    ) -> None:
        """
        Draw a bitmap on display at the specified column and row

        Args:
            bitmap (bitmap_module): The module containing the bitmap to draw
            x (int): column to start drawing at
            y (int): row to start drawing at
            index (int): Optional index of bitmap to draw from multiple bitmap
                module
        """
        ...

    def pbitmap(
        self, bitmap: ModuleType, x: int, y: int, index: int = ...
    ) -> None:
        """
        Draw a bitmap on display at the specified column and row one row at a time

        Args:
            bitmap (bitmap_module): The module containing the bitmap to draw
            x (int): column to start drawing at
            y (int): row to start drawing at
            index (int): Optional index of bitmap to draw from multiple bitmap
                module

        """
        ...

    def write(
        self,
        font: ModuleType,
        string: str,
        x: int,
        y: int,
        fg: int = ...,
        bg: int = ...
    ) -> None:
        """
        Write a string using a converted true-type font on the display starting
        at the specified column and row

        Args:
            font (font): The module containing the converted true-type font
            s (string): The string to write
            x (int): column to start writing
            y (int): row to start writing
            fg (int): foreground color, optional, defaults to WHITE
            bg (int): background color, optional, defaults to BLACK
        """
        ...

    def write_width(self, font: ModuleType, string: str):  # -> Literal[0]:
        """
        Returns the width in pixels of the string if it was written with the
        specified font

        Args:
            font (font): The module containing the converted true-type font
            string (string): The string to measure

        Returns:
            int: The width of the string in pixels

        """
        ...

    @micropython.native
    def polygon(
        self,
        points: tuple[int, int],
        x: int,
        y: int,
        color: int,
        angle: float = ...,
        center_x: int = ...,
        center_y: int = ...
    ) -> None:
        """
        Draw a polygon on the display.

        Args:
            points (list): List of points to draw.
            x (int): X-coordinate of the polygon's position.
            y (int): Y-coordinate of the polygon's position.
            color (int): 565 encoded color.
            angle (float): Rotation angle in radians (default: 0).
            center_x (int): X-coordinate of the rotation center (default: 0).
            center_y (int): Y-coordinate of the rotation center (default: 0).

        Raises:
            ValueError: If the polygon has less than 3 points.
        """
        ...
